### ISSUE TITLE
Project plan

### ISSUE THREAD

**Issue by christopherafbjur** [christopherafbjur/tretton37#3]
Aiming to score 12 points by implementing the following features:

### _design/accessibility

- [ ] Fancy animations (1 pt)
- [x] Responsive design, works on mobile and tablets (2pt)
- [x] No UI framework used (such as Bootstrap, Ant) (1pt)

### _functionality
- [x] Sort by name and office (1 pt)
- [x] Filter by name and office (1 pt)
- [ ] Available on a free public url (such as Azure, Heroku) (1 pt)
- [x] Only render a set of profiles using either infinity scroll, pagination or a load more button (2 pt)
- [x] Create custom API with webscraper (4pt)

### _testing/QA
- [x] Works in Chrome, Firefox, Edge (1 pt)
- [ ] Unit tests for existing functionality (reasonable coverage) (2 pt)
